### ISSUE TITLE
Configure HA only available on the Public network pages

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu-docs#1313]
### Describe the issue

Configuring HA is relevant for both network types, but arguable moreso for private networks. Can we index the page on both sides of the docs? 

### What page has the issue?

https://besu.hyperledger.org/en/latest/public-networks/how-to/configure-ha/?h=high+a

### Issue type

Confusing or misleading content

### Change suggestion

Have HA displayed on both sides, especially private networks. 

### Besu documentation issue guidelines

- [X] I read and followed this project's documentation guidelines.

**Comment by alexandratran** [comment]
@non-fungible-nelson When we did the restructure (splitting the docs into "public" and "private"), we realized it would be very difficult to have some pages display on both sections, without having to duplicate and maintain two copies of the page, which is not an ideal solution. The solution we settled on (which I think we discussed with you at the time) was to slightly sacrifice UX on the private networks side (since we're prioritizing public use cases currently). That is, any pages that apply to both public and private would be hosted on the public side, and the index pages on the private side would simply have a list of links to those pages on the public side. Additionally, the pages on the public side that apply to both would have tags for "private" and "public" at the top of the page.

On the [private networks "how to" index page](https://besu.hyperledger.org/en/latest/private-networks/how-to/), you can see that the Configure HA page is linked. And on the [Configure HA page](https://besu.hyperledger.org/en/latest/public-networks/how-to/configure-ha/), you can see that there's a "private networks" tag at the top of the page.

Unfortunately this isn't the ideal UX for private network developers, but it was the best and easiest to maintain solution the docs team could come up with, while optimizing the docs for public network developers. Let me know if you have more questions or ideas on this.
