### ISSUE TITLE
Document admin_reloadPlugin API

### ISSUE THREAD

**Issue by bgravenorst** [hyperledger/besu-docs#146]
Providing a new RPC method admin_reloadPlugin to dynamically (without the need to restart Besu) reload plugin config (this required a new reloadConfiguration method in Besu plugin api as it’s available for all plugins) see https://github.com/hyperledger/besu/pull/261

**Comment by NicolasMassart** [comment]
The method seems not to be called `admin_reloadPlugin` as indicated in #261 but looking at the code is seems to be `plugins_reloadPluginConfig` and have parameters. I think Parameters may be the name of the plugin that should be reloaded, but I still have to make sure as my last try was not working.

**Comment by MadelineMurray** [comment]
@NicolasMassart - once you get this working could you paste a working example into here Bryon can use.

**Comment by MadelineMurray** [comment]
Was there a CLI option related to this?

**Comment by NicolasMassart** [comment]
Yes both are available. A CLI to run indexing but requires to stop and rerun the node with the option, and an RPC method that can be called when the node is running. I Had the last details on how to use it yesterday from Abdel. Will write this here.

**Comment by NicolasMassart** [comment]
CLI command to run indexing is `besu operator generate-log-bloom-cache`
It requires to add all the options that you used if you used, for instance a specific datapath or genesis file or any custom option. Otherwise it will not index the right database.
This is to be run once every ~100K blocks but a new auto indexing feature is on it's way that will prevent the need to run it more than once: hyperledger/besu#367
But this CLI option is only if you already have a database with a non indexed chain.
If you run a new one hyperledger/besu#367 can run indexing directly as it syncs. You will have to explicitly activate  auto indexing with `--auto-logs-bloom-indexing-enabled` as it's `false` by default.

Then there's also an RPC method to run indexing without having to stop the node. See https://besu.hyperledger.org/en/latest/Reference/API-Methods/#admin_generatelogbloomcache
Even if the command line may be convenient sometimes, being able to run indexing without stopping the node is great. However, it requires RPC to be enables. So if you don't want to enable it for whatever reason, using the CLI is required.
The RPC method is `admin_generateLogBloomCache` form the **ADMIN** API (that must be enabled as it's not a default one). 
The method takes two parameters and in addition to what is documented already you could say that:
Start block: the block where you want Besu to start indexing
End block: the block where you want Besu to stop indexing
these blocks can take the following values : "earliest", "pending", "latest" or a block number (string with 0x prefix, 0x0 being the genesis file and so the same as "earliest").

**Comment by NicolasMassart** [comment]
No, only the RPC. No need for a CLI as it would mean that you stop and start Besu to run it, and if you do so, it reloads plugins. SO the only reason you need to reload is when you don't want to restart Besu, hence the RPC method. Will provide the method syntax here asap.

**Comment by NicolasMassart** [comment]
In theory, a sample request to reload a Kafka plugin config using RPC would be :
`{"jsonrpc":"2.0","method":"plugins_reloadPluginConfig","params":["tech.pegasys.plus.plugin.kafka.KafkaPlugin"],"id":1}`
But I'm having issues with internal error when trying this so I will add more details once I'm sure it works.

**Comment by NicolasMassart** [comment]
The issue on this Kafka example is related to some changes in the Event stream plugin (see private Jira https://pegasys1.atlassian.net/browse/PIE-2292).
Also I wonder, as the Kafka plugin is not open source, if we should use it as an example. But we have no open source plugins, so we may use a fake plugin name in our example request.
