### ISSUE TITLE
Advertised address/ports vs where to listen

### ISSUE THREAD

**Issue by hmijail** [hyperledger/besu-docs#332]
A frequent network configuration is NAT with port translation. In it, an application listens on a local IP:port, but is seen by the other side of the connection at a different IP:port. Hence, P2P applications usually have 2 different addresses to set: the IP&port where the application listens, and the IP&port which it advertises to peers so they can find it.

If such degree of configuration is not supported, then
* the P2P application depends on non-NATted peers to function
* peers need to be aware that the advertised address might be wrong and actively try to correct it
* a fix (that is not always possible) is to configure NAT to preserve port numbers

Failure to do these makes it hard to find / be found by peers.

In Besu's case, it's not clear whether NAT with port translation is supported.

https://besu.hyperledger.org/en/stable/HowTo/Find-and-Connect/Specifying-NAT/#manual says 
> By specifying MANUAL:
>    --p2p-host and --p2p-port define the **advertised** host and port for the P2P service.

But https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/#p2p-host says
> The host on which P2P **listens**. The default is 127.0.0.1.
(similarly so for --p2p-port)

One could infer that --p2p-host must be for advertising, since --p2p-interface can only be for listening (or are they overlapping?). But then what about --p2p-port? It seems to change the port at which Besu *listens*. 

Relatedly, if --p2p-host's default is 127.0.0.1 as the docs say, that would mean that
- either Besu is advertising an unreachable address, and so counting on peers to discard it (does Besu do that itself?),
- or it is opening its ports in an local-only address 

Both are surprising, so it would be good to know the implications/intended use cases.

**Comment by hmijail** [comment]
Finally some clarification in this thread: https://consensys.slack.com/archives/GM1C6LWCU/p1589074496297800

Summary:
NAT=NONE does not cause --p2p-host and --p2p-port to be ignored.
--p2p-host is the advertised host, NOT the host where Besu listens.

**Comment by hmijail** [comment]
Also: --rpc-http-host should have nothing do to with advertising, or even NAT in general. Seems to be on its way out: https://consensys.slack.com/archives/GAZBZB7KN/p1589092446319400

And no idea of what is the use of having both NAT=MANUAL and NAT=NONE, since both end up having the same effect. Looks like they might have some different use in the future? (also in that thread)

**Comment by ajsutton** [comment]
Please could we not link to private discussions on company specific slacks.  If there is relevant info there please include or summarise it here as most people will not have access to it.

**Comment by hmijail** [comment]
Fixed.

**Comment by NicolasMassart** [comment]
After some investigation, it seems that the understanding is due to the fact that the advertising can be influenced by the NAT option `--nat-method` in different ways depending on the option value: `UPNP`, `DOCKER`, `KUBERNETES`, `AUTO` and `NONE`. (since this issue was raised, the `MANUAL` value was removed).

**IMPORTANT:** Before creating issues in the project and asking dev to change the behaviour, my guess is that making the doc clear about how it works may be enough. There's one use case that can't really be achieved though, NAT=AUTO with a distinct port for listening locally and to advertise to the peers. But it never popped in support or community questions so filling this gap may be a useless development work for now and adding a clear doc is certainty enough.

NAT influences both P2P and JSON-RPC API because both are advertised in `eth_services` where their accesible IP/port are displayed. However, P2P also uses NAT to provide a meaningful enode address which is shared to peers and to return a result for `admin_nodeinfo`.

The 4 P2P parameters that are influenced by NAT are:

- listening interface (LI) is the local machine interface, defined by `--p2p-interface` CLI option, defaults to any interface (0.0.0.0).
- listening port (LP) is the local machine port defined by `--p2p-port` CLI option, defaults to 30303. It uses UDP for discovery and TCP for RLPX protocol.
- advertised host (AH) is the IP that is advertised in the `enode` address, `eth_services` and `admin_nodeinfo` and can be used to access the node from outside the network, defined by `--p2p-host` CLI option, defaults to 127.0.0.1
- advertised port (AP) is the port advertised in the `enode` address, `eth_services` and `admin_nodeinfo`, it defaults to the same value as LP.

## Behaviours depending on the NAT method:

### NAT == UPNP

  - LI configured by `--p2p-interface` or default value.
  - LP configured by `--p2p-port` or default value.
  - AH overridden by the value returned by the uPNP NAT manager. It's usually the Internet access point public IP.
  - AP is the same as LP and is the one forwarded by the access point as asked by the uPNP request. uPNP will be asked to open the same port over TCP and UDP for discovery and RPLX protocol.

### NAT ==  DOCKER

  - LI configured by `--p2p-interface` or default value.
  - LP configured by `--p2p-port` or default value.
  - AH overridden by the value returned by the Docker NAT manager. It uses the IP of the host on which the container runs.
  - AP is the host port mapped to LP by the docker publish feature. It requires that you ran your container with port publishing (`-p` docker option, for instance `-p 10101:30303` -> container internal port 30303 mapped to host port 10101). It will open the same port over TCP and UDP.

### NAT ==  KUBERNETES (K8s)

  - LI configured by `--p2p-interface` or default value.
  - LP configured by `--p2p-port` or default value.
  - AH overridden by the value returned by the K8s NAT manager. Depending on the K8s service type, it will either provide the cluster IP or load balancer IP.
  - AP is the port assigned to the service by K8s and returned by K8s service API. It will open the same port over TCP and UDP.

### NAT ==  NONE

  - LI configured by `--p2p-interface` or default value.
  - LP configured by `--p2p-port` or default value. Used over both TCP and UDP.
  - AH configured by `--p2p-host` or default value.
  - AP is the same as LP. Used over both TCP and UDP.

### NAT == auto

Will use the detected mode rules.

## NOTE

As you can see the only tricky part is that port can be different only for Docker and K8s.
For both uPNP and NONE, the port used to listen locally and to advertise is the same.
However if you need complex setup, it's very likely that you uses K8s and it's the recommended way.
uPNP and NONE are clearly targeting either individuals behind home router or devs with a local setup.

**Comment by hmijail** [comment]
> Before creating issues in the project and asking dev to change the behaviour, my guess is that making the doc clear about how it works may be enough. 

Totally agree. This issue asked for clarification, not for "dev to change the behaviour". 

> the only tricky part is that port can be different only for Docker and K8s.

Now that NAT==MANUAL has been removed, that part of uncertainty has been removed.
Other tricky parts remaining:

- There's no word of what happens if UPNP has been disabled ([as is typically recommended, since it's a security problem](https://fastestvpn.com/blog/what-is-upnp/)).
- If multiple Besu nodes are running behind NAT and all of them try to use the same port, the gateway needs to use multiple external ports.
  - UPNP can not make the same port available to all of them. What does UPNP do if the external port is already in use? Does it just fail, or report back to the requester a different opened port? Does Besu deal with those possibilities?
  - Manual settings can fix this in the gateway. But for that, the advertising mechanism needs to be able to deal with different listening and advertised ports. Does Besu / the protocol deal with that complexity automatically? (as an example, libp2p seems to do it automatically and not allow manual configuration, at least in some of its implementations, because it explicitly deals with the problem internally. On the other hand, bittorrent and other p2p clients typically allow to specify both ports)

All of this is to bring attention to network configuration complexity that seemingly is not being addressed. Whether that is important or not for Besu, I have no idea.

**Comment by NicolasMassart** [comment]
> - UPNP can not make the same port available to all of them. What does UPNP do if the external port is already in use? Does it just fail, or report back to the requester a different opened port? Does Besu deal with those possibilities?
> - Manual settings can fix this in the gateway. But for that, the advertising mechanism needs to be able to deal with different listening and advertised ports. Does Besu / the protocol deal with that complexity automatically?

The uPNP protocol requires the requester to specify the external port to use. The library used by Besu is `jupnp` and this is confirmed by its API.

When an error occurs (not able to create the port mapping for any reason including because the external port is already in use), an exception is thrown and a warning log is displayed.

If we want to be able to run multiple instances with different external ports automatically determined on the uPNP to prevent external port collisions, the logic should then be implemented in the Besu code to look for already mapped ports on the router and change the request for a not already used remote port accordingly.
This is probably not a required change here though as if multiple services running and being advertised outside may be the case in entreprise or production context, uPNP is clearly for personal use on a home network and the chances that the conflicts happens are small and the consequences are not critical.

Documenting the limitations is then probably enough for all this ports subject.
