### ISSUE TITLE
Security Module Plugin: getPublicKey called before Security Module Plugin start.

### ISSUE THREAD

**Issue by magooster** [hyperledger/besu-docs#406]
### Steps to Reproduce (Bug)
1. Installed a custom security module plugin.
2. Configure blockchain network for ibft2 or clique consensus in genesis block.
3. Start the node.

**Expected behavior:** [What you expect to happen]

Node uses security module for all node 'key' (cryptographic) operations

**Actual behavior:** [What actually happens]

Get a null pointer error as the configured controller tries to get the node public key before plugin 'start'. 

**Frequency:** [What percentage of the time does it occur?]

Always

### Versions (Add all that apply)
* Software version: 1.4.5

### Additional Information

Looking at BesuCommand run method, the controller is constructed before the plugins are started.

Using the 'register' phase of the plugin lifecycle would mean command line options are not available.

**Comment by NicolasMassart** [comment]
Comment with more details from Trent made after merge:

> rain-on 7 hours ago Member
personally I think the message almost needs to be:
It is recognised that an additional step may need to exist in the plugin lifecycle, in between register and start.
The issue being that inter-module dependencies may mean that some modules need to be ready prior to start being executed.
>If your plugin is required to offer service prior to "start" phase (and the plugin lifecycle hasn't be updated yet), it is recommended that the following work around be used by plugin developers:
>
>During register phase
** register required cmdline options with the PicoCli service (as normal)
** Register a memoised supplier of your service with the BesuContext (as you are unable to register a concrete version due to lack of cmdline args being available)
During the start phase - take any further actions required.
The goal being, that when the core Besu engine attempts to use your plugin (which is guaranteed to occur after cmdline parsing, but may be before "start") the memoised supplier will be executed, and will thus create the concrete service on first usage (rather than at start).

I think it's going too deep in details for the user doc. I added the comment here so that readers can find it without going in the PR, but it's just the same comment. When we will have a plugin dev doc, we will be able to add this, but at this point maybe the issue will be fixed...
